services:
  greetingcard:
    build: .
    container_name: greetingcard
    restart: unless-stopped
    volumes:
      - greetingcard-data:/data
    networks:
      - traefik_web
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_web
      - traefik.http.routers.greetingcard.rule=Host(`cards.retrobit.me`)
      - traefik.http.routers.greetingcard.tls=true
      - traefik.http.routers.greetingcard.tls.certresolver=lets-encrypt
      - traefik.http.services.greetingcard.loadbalancer.server.port=8000

volumes:
  greetingcard-data:

networks:
  traefik_web:
    external: true
